version: '3.8'

services:

  # Backend
  fastapi:
    build:
      context: ./backend/
    container_name: Fastapi
    restart: always
    command: uvicorn backend:app --reload --host=0.0.0.0 --port=8000
    volumes:
      - ./backend:/app/
    ports:
     - 8000:8000
    networks:
      - project_network

  # Frontend
  streamlit:
    build:
      context: ./frontend/
    container_name: Streamlit
    restart: always
    command: streamlit run frontend.py
    volumes:
      - ./frontend:/app/
    ports:
      - 8501:8501
    networks:
      - project_network
    depends_on:
      - fastapi
      
networks:
  project_network:
    driver: bridge