# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mybackendapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # TESTS
  test:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Install the dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: black - PEP8 code formatting
      run: |
        black backend.py

    - name: isort - Sort the librairies
      run: |
        isort backend.py --profile=black

    - name: flake8 - Linter
      run: |
        flake8 --ignore=F401

    - name: Pytest
      run: |
        pytest

  # BUILD
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://backendfixed.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_18452e376abd4f3982d1c473334fac17 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f5981f4c9d8d4de7b826c2dadac3a5cf }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: backendfixed.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_18452e376abd4f3982d1c473334fac17 }}/backendfinal:${{ github.sha }}
        file: ./Dockerfile

  # DEPLOY
  deploy:
    runs-on: 'ubuntu-latest'
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mybackendapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f7fec46b50e54d579febd0eb26165232 }}
        images: 'backendfixed.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_18452e376abd4f3982d1c473334fac17 }}/backendfinal:${{ github.sha }}'